#!/usr/bin/env bash
set -euo pipefail

USAGE="Usage: $0 [--mode local|gcp] [--gpu t4|a100|a100-2g|a100-4g|a100-8g] [--no-idempotent] [--force-modulate] [--label LABEL]"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LANG_DIR="$SCRIPT_DIR/../../modulators/language"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
CLI_TOKEN_FILE="$SCRIPT_DIR/.cli_token"
SESSION_FILE="${HOME}/.ephapsys_state/session.json"

MODE="local"
GPU="t4"
IDEMPOTENT=1
FORCE_MODULATE=0
SKIP_BUILD_FLAG=""
SKIP_PUSH_FLAG=""
LABEL=""
BLUE="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
MAGENTA="\033[35m"
GOLD="\033[38;5;220m"
RESET="\033[0m"

info() {
  printf "${BLUE}[INFO]${RESET} %s\n" "$*"
}

warn() {
  printf "${YELLOW}[WARN]${RESET} %s\n" "$*" >&2
}

error() {
  printf "${MAGENTA}[ERROR]${RESET} %s\n" "$*" >&2
}

require_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || {
    error "Missing required command: $cmd"
    exit 1
  }
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    --local)
      MODE="local"
      shift
      ;;
    --gcp)
      MODE="gcp"
      shift
      ;;
    --gpu)
      MODE="gcp"
      GPU="$2"
      shift 2
      ;;
    --idempotent)
      IDEMPOTENT=1
      shift
      ;;
    --no-idempotent)
      IDEMPOTENT=0
      shift
      ;;
    --force-modulate)
      FORCE_MODULATE=1
      shift
      ;;
    --no-build)
      SKIP_BUILD_FLAG="--no-build"
      shift
      ;;
    --no-push)
      SKIP_PUSH_FLAG="--no-push"
      shift
      ;;
    --label)
      LABEL="$2"
      shift 2
      ;;
    -h|--help)
      echo "$USAGE"
      exit 0
      ;;
    *)
      error "Unknown argument: $1"
      echo "$USAGE"
      exit 1
      ;;
  esac
done

case "$MODE" in
  local|gcp) ;;
  *)
    error "--mode must be one of: local, gcp"
    exit 1
    ;;
esac

require_cmd curl
require_cmd jq
require_cmd python3

if [[ ! -f "$ENV_FILE" && -f "$ENV_EXAMPLE" ]]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  info "Created $ENV_FILE from .env.example. Fill in AOC_ORG_ID, AOC_PROVISIONING_TOKEN, and AOC_MODULATION_TOKEN, then rerun."
  exit 0
fi

if [[ ! -f "$ENV_FILE" ]]; then
  error "Missing $ENV_FILE"
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

AOC_API="${AOC_BASE_URL:-${AOC_API_URL:-${AOC_API_BASE:-${AOC_API:-http://localhost:7001}}}}"
CLI_API="${AOC_API}/cli"
ORG_ID="${AOC_ORG_ID:-}"
API_TOKEN="${API_TOKEN:-${AOC_MODULATION_TOKEN:-}}"
HF_TOKEN="${HF_TOKEN:-}"
MODEL_REPO="${HELLOWORLD_MODEL_REPO:-Qwen/Qwen3.5-0.8B}"
MODEL_REVISION="${HELLOWORLD_MODEL_REVISION:-main}"
MODEL_KIND="${HELLOWORLD_MODEL_KIND:-language}"
MODEL_NAME="${HELLOWORLD_MODEL_NAME:-HelloWorld Starter Model}"
AGENT_LABEL="${LABEL:-${AGENT_TEMPLATE_NAME:-HelloWorld Agent Template}}"
AGENT_DESCRIPTION="${HELLOWORLD_AGENT_DESCRIPTION:-Starter HelloWorld agent template generated by push.sh}"
DEFAULT_POLICY_JSON='[{"type":"output_moderation","value":{"categories":["self-harm","violence"],"action":"block"},"status":"active"},{"type":"prompt_injection_defense","value":{"action":"block"},"status":"active"}]'

model_size_label() {
  case "$MODEL_REPO" in
    Qwen/Qwen3.5-0.8B) printf '0.8B params';;
    google/flan-t5-small) printf '~80M params';;
    *) printf 'size not annotated';;
  esac
}

print_plan() {
  local publish_mode="full modulation"
  local plan_label="${MODEL_NAME:-Starter Model}"
  if [[ "$IDEMPOTENT" -eq 1 ]]; then
    publish_mode="idempotent publish"
  fi
  printf "\n${GOLD}%s${RESET}\n" "$plan_label"
  printf "  Target AOC:       %s\n" "$AOC_API"
  printf "  Runtime mode:     %s\n" "$MODE"
  printf "  Model repo:       %s\n" "$MODEL_REPO"
  printf "  Model size:       %s\n" "$(model_size_label)"
  printf "  Publish mode:     %s\n" "$publish_mode"
  printf "  Agent template:   %s\n\n" "$AGENT_LABEL"
}

step() {
  printf "${GOLD}[STEP]${RESET} %s\n" "$*"
}

progress() {
  if [[ -t 1 ]]; then
    printf "\r\033[2K${GOLD}[WAIT]${RESET} %s" "$*"
  else
    printf "${GOLD}[WAIT]${RESET} %s\n" "$*"
  fi
}

progress_done() {
  if [[ -t 1 ]]; then
    printf "\r\033[2K"
  fi
}

if [[ -z "$ORG_ID" ]]; then
  error "AOC_ORG_ID must be set in $ENV_FILE"
  exit 1
fi

if [[ -z "$API_TOKEN" ]]; then
  error "AOC_MODULATION_TOKEN (or API_TOKEN) must be set in $ENV_FILE"
  exit 1
fi

AUTH_HEADER=(-H "Authorization: Bearer ${API_TOKEN}")

save_env_var() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i '' "s|^${key}=.*|${key}=${value}|" "$ENV_FILE" 2>/dev/null || sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf '\n%s=%s\n' "$key" "$value" >>"$ENV_FILE"
  fi
}

cli_login() {
  local token=""
  local session_base_url=""
  if [[ -f "$SESSION_FILE" ]]; then
    token=$(jq -r '.token // empty' "$SESSION_FILE" 2>/dev/null || true)
    session_base_url=$(jq -r '.base_url // empty' "$SESSION_FILE" 2>/dev/null || true)
    if [[ -n "$token" ]]; then
      local code
      code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $token" "$CLI_API/models/list")
      if [[ "$code" == "200" ]]; then
        info "Reusing CLI session from ~/.ephapsys_state/session.json" >&2
        printf '%s' "$token"
        return
      fi
      if [[ -n "$session_base_url" && "$session_base_url" != "$AOC_API" ]]; then
        warn "Saved CLI session targets $session_base_url but push.sh is targeting $AOC_API" >&2
      fi
    fi
  fi
  if [[ -f "$CLI_TOKEN_FILE" ]]; then
    token=$(cat "$CLI_TOKEN_FILE")
    local code
    code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $token" "$CLI_API/models/list")
    if [[ "$code" == "200" ]]; then
      info "Reusing cached CLI token from .cli_token" >&2
      printf '%s' "$token"
      return
    fi
  fi

  if [[ ! -t 0 ]]; then
    error "No valid CLI session found for model registration. Run 'ephapsys login' first, then rerun push.sh."
    exit 1
  fi

  warn "No reusable CLI session found for ${AOC_API}; falling back to interactive CLI login." >&2

  local cli_user cli_pass login_resp
  read -r -p "Enter CLI username (email): " cli_user
  read -r -s -p "Enter CLI password: " cli_pass
  printf '\n'
  login_resp=$(curl -sS -X POST "$CLI_API/login" \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"${cli_user}\",\"password\":\"${cli_pass}\"}")
  token=$(echo "$login_resp" | jq -r '.token // empty')
  if [[ -z "$token" ]]; then
    error "CLI login failed"
    echo "$login_resp" >&2
    exit 1
  fi
  printf '%s' "$token" >"$CLI_TOKEN_FILE"
  mkdir -p "$(dirname "$SESSION_FILE")"
  jq -n --arg token "$token" --arg base_url "$AOC_API" --argjson raw "$login_resp" '
    ($raw | if type == "object" then . else {} end) + {token: $token, base_url: $base_url}
  ' >"$SESSION_FILE"
  printf '%s' "$token"
}

fetch_model_templates() {
  curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/models?type=TEMPLATE"
}

resolve_model_template() {
  fetch_model_templates | jq -r --arg repo "$MODEL_REPO" --arg kind "$MODEL_KIND" --arg name "$MODEL_NAME" '
    (.items // [])
    | map(select((((.model_kind // .kind // "") | ascii_downcase) == ($kind | ascii_downcase))
      and ((.source_repo // "") == $repo or (.name // "") == $name or (.name // "") == ("HuggingFace " + $repo))))
    | sort_by(.created_at // 0)
    | last
    | (.ID // .public_id // .internal_id // ._id // empty)'
}

register_model_template() {
  local cli_token="$1"
  local payload
  local response
  local ok
  cli_token="$(printf '%s' "$cli_token" | tr -d '\r\n')"
  step "Registering model template in AOC for ${MODEL_REPO}"
  payload=$(jq -n \
    --arg provider "huggingface" \
    --arg model_repo "$MODEL_REPO" \
    --arg revision "$MODEL_REVISION" \
    --arg model_name "$MODEL_NAME" \
    --arg model_kind "$MODEL_KIND" \
    --arg hf_token "$HF_TOKEN" \
    '{
      provider: $provider,
      ids: [$model_repo],
      repo_id: $model_repo,
      revision: $revision,
      auto_register: true,
      name: $model_name,
      model_kind: $model_kind,
      hf_token: $hf_token
    }')
  response=$(curl -sS -X POST "$CLI_API/models/register" \
    -H "Authorization: Bearer ${cli_token}" \
    -H "Content-Type: application/json" \
    -d "$payload")
  ok=$(printf '%s' "$response" | jq -r '.ok // empty' 2>/dev/null || true)
  if [[ "$ok" != "true" ]]; then
    error "Model registration failed"
    printf '%s\n' "$response" >&2
    exit 1
  fi
  info "Model registration request accepted by AOC."
}

model_ready() {
  local model_id="$1"
  curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/models/${model_id}" | jq -e '
    (
      (.Modulated // false) == true
      or (.Modulation.status // "") == "completed"
      or (
        (.Modulation.status // "") == "idempotent"
        and ((.Modulation.finished_at // 0) > 0)
      )
    )
    and (
      (((.artifact_urls // {}) | length) > 0)
      or ((.artifact_url // "") != "")
      or ((.storage_path // "") != "")
      or ((((.Modulation.artifact_urls // {}) | length)) > 0)
      or ((.Modulation.ecm_digest // "") != "")
    )' >/dev/null
}

poll_until_ready() {
  local model_id="$1"
  local timeout="${2:-7200}"
  local interval="${3:-5}"
  local deadline=$(( $(date +%s) + timeout ))
  local started=$(( $(date +%s) ))
  local -a spinner=('|' '/' '-' '\\')
  local spin_idx=0
  step "Waiting for model template ${model_id} to become ready"
  while true; do
    if model_ready "$model_id"; then
      local elapsed=$(( $(date +%s) - started ))
      progress_done
      printf "${GREEN}[DONE]${RESET} Model template %s is ready after %ss.\n" "$model_id" "$elapsed"
      return 0
    fi
    if (( $(date +%s) >= deadline )); then
      progress_done
      error "Timed out waiting for model template ${model_id} to become ready"
      return 1
    fi
    local status_line
    status_line="$(curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/models/${model_id}" | jq -r '
      [
        ("status=" + ((.Modulation.status // .status // "unknown") | tostring)),
        ("modulated=" + (((.Modulated // false) | tostring))),
        ("artifacts=" + (((((.artifact_urls // {}) | length) + ((.Modulation.artifact_urls // {}) | length))) | tostring))
      ] | join(", ")
    ' 2>/dev/null || printf 'status=unknown')"
    local elapsed=$(( $(date +%s) - started ))
    progress "${spinner[$spin_idx]} ${elapsed}s  ${status_line}"
    spin_idx=$(( (spin_idx + 1) % ${#spinner[@]} ))
    sleep "$interval"
  done
}

trigger_idempotent_publish() {
  local model_id="$1"
  step "Triggering idempotent publish for ${model_id}"
  curl -sS -X POST "${AOC_API}/modulation/start" \
    "${AUTH_HEADER[@]}" \
    -H "Content-Type: application/json" \
    -d "{
      \"model_template_id\": \"${model_id}\",
      \"skip_modulation\": true,
      \"mode\": \"auto\",
      \"variant\": \"baseline\",
      \"kpi\": {\"targets\": [], \"maxSteps\": 1}
    }" >/dev/null
}

MOD_ENV_BACKUP=""
cleanup_mod_env() {
  if [[ -n "$MOD_ENV_BACKUP" && -f "$MOD_ENV_BACKUP" ]]; then
    mv "$MOD_ENV_BACKUP" "$LANG_DIR/.env"
  else
    rm -f "$LANG_DIR/.env"
  fi
}

prepare_modulator_env() {
  if [[ -f "$LANG_DIR/.env" ]]; then
    MOD_ENV_BACKUP="$LANG_DIR/.env.bak.push.$$"
    cp "$LANG_DIR/.env" "$MOD_ENV_BACKUP"
  fi
  cat >"$LANG_DIR/.env" <<EOF
BASE_URL=${AOC_API}
AOC_ORG_ID=${ORG_ID}
AOC_MODULATION_TOKEN=${API_TOKEN}
MODEL_TEMPLATE_ID=${MODEL_TEMPLATE_ID}
OUTDIR=./artifacts
HF_TOKEN=${HF_TOKEN}
EOF
}

run_modulation() {
  trap cleanup_mod_env RETURN
  prepare_modulator_env
  if [[ "$IDEMPOTENT" -eq 1 ]]; then
    trigger_idempotent_publish "$MODEL_TEMPLATE_ID"
    poll_until_ready "$MODEL_TEMPLATE_ID"
    return
  fi
  if [[ "$MODE" == "local" ]]; then
    info "Running language modulation locally..."
    (cd "$LANG_DIR" && ./modulate_local.sh)
  else
    info "Running language modulation on GCP (gpu=${GPU})..."
    (cd "$LANG_DIR" && ./modulate_gcp.sh "$GPU" ${SKIP_BUILD_FLAG:+$SKIP_BUILD_FLAG} ${SKIP_PUSH_FLAG:+$SKIP_PUSH_FLAG})
  fi
  poll_until_ready "$MODEL_TEMPLATE_ID"
}

resolve_agent_template() {
  curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/agents?type=TEMPLATE" | jq -r --arg label "$AGENT_LABEL" '
    map(select((.label // "") == $label))
    | first
    | (.id // .public_id // .ID // ._id // empty)'
}

create_agent_template() {
  local payload
  payload=$(jq -n \
    --arg label "$AGENT_LABEL" \
    --arg description "$AGENT_DESCRIPTION" \
    --arg model_id "$MODEL_TEMPLATE_ID" \
    --argjson policies "$DEFAULT_POLICY_JSON" '
      {
        label: $label,
        description: $description,
        type: "TEMPLATE",
        models: [
          {
            id: $model_id,
            config: {
              type: "language",
              policies: $policies
            }
          }
        ]
      }')
  curl -sS -X POST "${AOC_API}/agents" \
    "${AUTH_HEADER[@]}" \
    -H "Content-Type: application/json" \
    -d "$payload"
}

MODEL_TEMPLATE_ID="$(resolve_model_template || true)"
print_plan
step "Resolving existing model template"
if [[ -z "$MODEL_TEMPLATE_ID" ]]; then
  CLI_TOKEN="$(cli_login)"
  register_model_template "$CLI_TOKEN"
  step "Refreshing model template lookup after registration"
  MODEL_TEMPLATE_ID="$(resolve_model_template || true)"
fi

if [[ -z "$MODEL_TEMPLATE_ID" ]]; then
  error "Failed to resolve language model template for ${MODEL_REPO}"
  exit 1
fi

info "Resolved language model template: ${MODEL_TEMPLATE_ID}"
save_env_var MODEL_TEMPLATE_ID "$MODEL_TEMPLATE_ID"

if [[ "$FORCE_MODULATE" -eq 1 ]] || ! model_ready "$MODEL_TEMPLATE_ID"; then
  if [[ "$IDEMPOTENT" -eq 1 ]]; then
    step "Publishing model template via idempotent path"
  else
    step "Publishing model template via full modulation path"
  fi
  run_modulation
else
  info "Model template already modulated and ready; skipping modulation."
fi

step "Resolving existing agent template"
AGENT_TEMPLATE_ID="$(resolve_agent_template || true)"
if [[ -z "$AGENT_TEMPLATE_ID" ]]; then
  step "Creating agent template: ${AGENT_LABEL}"
  RESP="$(create_agent_template)"
  AGENT_TEMPLATE_ID="$(echo "$RESP" | jq -r '.id // .public_id // .ID // ._id // .agent.id // .agent.public_id // empty')"
else
  warn "Agent template '${AGENT_LABEL}' already exists; reusing it."
fi

if [[ -z "$AGENT_TEMPLATE_ID" ]]; then
  error "Failed to create or resolve HelloWorld agent template"
  exit 1
fi

save_env_var AGENT_TEMPLATE_ID "$AGENT_TEMPLATE_ID"

cat <<EOF

[SUCCESS] HelloWorld bootstrap complete.
  MODE:              ${MODE}
  MODEL_TEMPLATE_ID: ${MODEL_TEMPLATE_ID}
  AGENT_TEMPLATE_ID: ${AGENT_TEMPLATE_ID}

Next:
  ./run.sh --local         # runs preflight automatically, then starts the HelloWorld agent locally
EOF
